### PR TITLE
Support iOS 8 and OS X 10.9

### PR DESCRIPTION
**Pull request by nvzqz**
Now that [SipHash](https://github.com/lorentey/SipHash) supports these OS versions as of https://github.com/lorentey/SipHash/pull/1, so should BigInt.

### CODE REVIEW

**Comment by lorentey** [comment]
Yep! But SipHash should be released first.

**Comment by nvzqz** [comment]
Waiting on that, and then I'll make the changes on this branch or you can make the appropriate changes yourself.

**Comment by lorentey** [comment]
SipHash 1.1.0 is out; let's see if BigInt builds now

**Comment by lorentey** [comment]
👍

**Comment by nvzqz** [comment]
Great, now [RandomKitBigInt](https://github.com/nvzqz/RandomKitBigInt) can support these platforms too upon the next release of BigInt.

**Comment by lorentey** [comment]
I'll make a release in a moment.

**Pull request merged**
